# Generated by Django 4.2.2 on 2024-04-15 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaMaritima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('telefono', models.CharField(default='', max_length=100, verbose_name='telefono')),
            ],
            options={
                'db_table': 'AgenciaMaritima',
            },
        ),
        migrations.CreateModel(
            name='Armadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('direccion', models.CharField(blank=True, default='', max_length=150, verbose_name='direccion')),
                ('cuit', models.CharField(blank=True, default='', max_length=13, verbose_name='cuit')),
                ('telefono', models.CharField(default='', max_length=100, verbose_name='telefono')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('agenciaMaritima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.agenciamaritima')),
            ],
            options={
                'db_table': 'Armadora',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Barco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='nombre')),
                ('tipo', models.CharField(default='', max_length=15, verbose_name='tipo')),
                ('matricula', models.CharField(default='', max_length=15, verbose_name='matricula')),
                ('bandera', models.CharField(default='', max_length=30, verbose_name='bandera')),
                ('eslora', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True, verbose_name='eslora')),
                ('manga', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True, verbose_name='manga')),
                ('puntal', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True, verbose_name='puntal')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('armadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.armadora')),
            ],
            options={
                'db_table': 'Barco',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='', max_length=100, verbose_name='marca')),
                ('patente', models.CharField(default='', max_length=15, verbose_name='patente')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Camion',
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitioPuerto', models.CharField(choices=[(' ', ' '), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('MUELLE NUEVO', 'MUELLE NUEVO'), ('MUELLE CONARPESA', 'MUELLE CONARPESA'), ('MUELLE JUAN GRANADA', 'MUELLE JUAN GRANADA'), ('MUELLE CABO VIRGENES', 'MUELLE CABO VIRGENES'), ('MUELLE CAMARONES', 'MUELLE CAMARONES'), ('MUELLE S.A.O', 'MUELLE S.A.O'), ('MUELLE S.A.E', 'MUELLE S.A.E')], default='', max_length=50, verbose_name='sitioPuerto')),
                ('densidad', models.DecimalField(decimal_places=4, default='1', max_digits=10, null=True, verbose_name='densidad')),
                ('temperatura', models.DecimalField(decimal_places=2, default='1', max_digits=10, null=True, verbose_name='temperatura')),
                ('fechaHoraInicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('barco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.barco')),
            ],
            options={
                'db_table': 'Carga',
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(default='', max_length=100, verbose_name='apellido')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='nombre')),
                ('dni', models.CharField(default='', max_length=10, null=True, verbose_name='dni')),
                ('telefono', models.CharField(default='', max_length=50, verbose_name='telefono')),
                ('domicilio', models.CharField(default='', max_length=100, verbose_name='domicilio')),
                ('nacionalidad', models.CharField(default='', max_length=100, verbose_name='nacionalidad')),
                ('pna', models.CharField(default='', max_length=20, null=True, verbose_name='pna')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Chofer',
            },
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='nombre')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Combustible',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=100, verbose_name='empresa')),
                ('titularEmpresa', models.CharField(default='', max_length=100, verbose_name='titularEmpresa')),
                ('direccionEmpresa', models.CharField(default='', max_length=100, verbose_name='direccionEmpresa')),
                ('cuitEmpresa', models.CharField(default='', max_length=15, verbose_name='cuitEmpresa')),
                ('telefonoEmpresa', models.CharField(default='', max_length=100, verbose_name='telefonoEmpresa')),
                ('emailEmpresa', models.EmailField(default='', max_length=50, null=True, verbose_name='emailEmpresa')),
                ('certificadoInscripcion', models.CharField(default='', max_length=20, verbose_name='certificadoInscripcion')),
                ('vencimientoCertificadoInscripcion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='vencimientoCertificadoInscripcion')),
                ('aseguradoraChoferes', models.CharField(default='', max_length=20, verbose_name='aseguradoraChoferes')),
                ('vencimientoAseguradora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='vencimientoAseguradora')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Configuracion',
            },
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Puerto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Remolque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='', max_length=100, verbose_name='marca')),
                ('patente', models.CharField(default='', max_length=15, verbose_name='patente')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Remolque',
            },
        ),
        migrations.CreateModel(
            name='RemitoVarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporte', models.CharField(choices=[('OJR ', 'OJR'), ('NAO', 'NAO')], default='', max_length=10, verbose_name='transporte')),
                ('destinatario', models.CharField(default='', max_length=100, verbose_name='destinatario')),
                ('lugarEntrega', models.CharField(default='', max_length=100, verbose_name='lugarEntrega')),
                ('IVA', models.CharField(choices=[('TN ', 'TN'), ('LTS', 'LTS')], default='', max_length=5, verbose_name='IVA')),
                ('cantidad', models.IntegerField(default='1', null=True, verbose_name='cantidad')),
                ('unidad', models.CharField(choices=[('TN ', 'TN'), ('LTS', 'LTS')], default='', max_length=10, verbose_name='unidad')),
                ('numero', models.IntegerField(default='1', null=True, verbose_name='numero')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('camion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.camion')),
                ('chofer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.chofer')),
                ('remolque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.remolque')),
            ],
            options={
                'db_table': 'RemitoVarios',
            },
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporte', models.CharField(choices=[('OJR ', 'OJR'), ('NAO', 'NAO')], default='', max_length=10, verbose_name='transporte')),
                ('numero', models.IntegerField(default='1', null=True, verbose_name='numero')),
                ('cantidadBarco', models.IntegerField(default='1', null=True, verbose_name='cantidadBarco')),
                ('cantidadDeposito', models.IntegerField(default='1', null=True, verbose_name='cantidadDeposito')),
                ('camion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.camion')),
                ('carga', models.ForeignKey(db_column='carga_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOJR.carga')),
                ('chofer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.chofer')),
                ('remolque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.remolque')),
            ],
            options={
                'db_table': 'Remito',
            },
        ),
        migrations.AddField(
            model_name='carga',
            name='combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.combustible'),
        ),
        migrations.AddField(
            model_name='carga',
            name='puerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.puerto'),
        ),
    ]
