# Generated by Django 4.2.2 on 2025-12-14 19:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaMaritima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('telefono', models.CharField(default='', max_length=100, verbose_name='telefono')),
            ],
            options={
                'db_table': 'AgenciaMaritima',
            },
        ),
        migrations.CreateModel(
            name='Armadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('direccion', models.CharField(blank=True, default='', max_length=150, verbose_name='direccion')),
                ('cuit', models.CharField(blank=True, default='', max_length=13, verbose_name='cuit')),
                ('telefono', models.CharField(default='', max_length=100, verbose_name='telefono')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('agenciaMaritima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.agenciamaritima')),
            ],
            options={
                'db_table': 'Armadora',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Barco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='nombre')),
                ('tipo', models.CharField(default='', max_length=15, verbose_name='tipo')),
                ('matricula', models.CharField(default='', max_length=15, verbose_name='matricula')),
                ('bandera', models.CharField(default='', max_length=30, verbose_name='bandera')),
                ('eslora', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True, verbose_name='eslora')),
                ('manga', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True, verbose_name='manga')),
                ('puntal', models.DecimalField(decimal_places=2, default='', max_digits=10, null=True, verbose_name='puntal')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('armadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.armadora')),
            ],
            options={
                'db_table': 'Barco',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='', max_length=100, verbose_name='marca')),
                ('patente', models.CharField(default='', max_length=15, verbose_name='patente')),
                ('habilitadoAFIP', models.BooleanField(default=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Camion',
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitioPuerto', models.CharField(choices=[(' ', ' '), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('MUELLE NUEVO', 'MUELLE NUEVO'), ('MUELLE CONARPESA', 'MUELLE CONARPESA'), ('MUELLE JUAN GRANADA', 'MUELLE JUAN GRANADA'), ('MUELLE JUAN GRANADA 3', 'MUELLE JUAN GRANADA 3'), ('MUELLE CABO VIRGENES', 'MUELLE CABO VIRGENES'), ('MUELLE CAMARONES', 'MUELLE CAMARONES'), ('MUELLE S.A.O', 'MUELLE S.A.O'), ('MUELLE S.A.E', 'MUELLE S.A.E')], default='', max_length=50, verbose_name='sitioPuerto')),
                ('densidad', models.DecimalField(decimal_places=4, default='1', max_digits=10, null=True, verbose_name='densidad')),
                ('temperatura', models.DecimalField(decimal_places=2, default='1', max_digits=10, null=True, verbose_name='temperatura')),
                ('exentoRancho', models.BooleanField(default=False)),
                ('nroRancho', models.IntegerField(blank=True, null=True, verbose_name='nroRancho')),
                ('letraRancho', models.CharField(blank=True, max_length=1, null=True, verbose_name='letraRancho')),
                ('ordenCompra', models.CharField(blank=True, max_length=100, null=True, verbose_name='ordenCompra')),
                ('fechaInicio', models.DateField(default=django.utils.timezone.now)),
                ('horaInicio', models.TimeField(blank=True, null=True)),
                ('barco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.barco')),
            ],
            options={
                'db_table': 'Carga',
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(default='', max_length=100, verbose_name='apellido')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='nombre')),
                ('dni', models.CharField(default='', max_length=10, null=True, verbose_name='dni')),
                ('telefono', models.CharField(default='', max_length=50, verbose_name='telefono')),
                ('domicilio', models.CharField(default='', max_length=100, verbose_name='domicilio')),
                ('nacionalidad', models.CharField(default='', max_length=100, verbose_name='nacionalidad')),
                ('pna', models.CharField(default='', max_length=20, null=True, verbose_name='pna')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Chofer',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(default='', max_length=100, verbose_name='denominacion')),
                ('cuit', models.CharField(blank=True, default='', max_length=13, verbose_name='cuit')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='nombre')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Combustible',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='', max_length=100, verbose_name='empresa')),
                ('titularEmpresa', models.CharField(default='', max_length=100, verbose_name='titularEmpresa')),
                ('direccionEmpresa', models.CharField(default='', max_length=100, verbose_name='direccionEmpresa')),
                ('cuitEmpresa', models.CharField(default='', max_length=15, verbose_name='cuitEmpresa')),
                ('telefonoEmpresa', models.CharField(default='', max_length=100, verbose_name='telefonoEmpresa')),
                ('emailEmpresa', models.EmailField(default='', max_length=50, null=True, verbose_name='emailEmpresa')),
                ('certificadoInscripcion', models.CharField(default='', max_length=20, verbose_name='certificadoInscripcion')),
                ('vencimientoCertificadoInscripcion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='vencimientoCertificadoInscripcion')),
                ('aseguradoraChoferes', models.CharField(default='', max_length=20, verbose_name='aseguradoraChoferes')),
                ('vencimientoAseguradora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='vencimientoAseguradora')),
                ('impresoraRemitos', models.CharField(choices=[('LaserNuria', 'LaserNuria'), ('Brother', 'Brother')], max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Configuracion',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(default='', max_length=100, verbose_name='denominacion')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('codigoAduana', models.IntegerField(null=True, verbose_name='codigoAduana')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Puerto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(default='', max_length=10, verbose_name='abreviatura')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='nombre')),
                ('cuit', models.CharField(blank=True, default='', max_length=13, verbose_name='cuit')),
            ],
            options={
                'db_table': 'Transporte',
            },
        ),
        migrations.CreateModel(
            name='Remolque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='', max_length=100, verbose_name='marca')),
                ('patente', models.CharField(default='', max_length=15, verbose_name='patente')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.transporte')),
            ],
            options={
                'db_table': 'Remolque',
            },
        ),
        migrations.CreateModel(
            name='RemitoVarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('OJR', 'OJR'), ('NAO', 'NAO')], default='', max_length=10, verbose_name='empresa')),
                ('transporte', models.CharField(choices=[('OJR ', 'Orlando Jorge Robert'), ('JPM', 'Juan Pedro Mairal'), ('VESPRINI', 'Vesprini'), ('TRC', 'Transcont')], default='', max_length=10, verbose_name='transporte')),
                ('producto', models.CharField(default='', max_length=100, verbose_name='producto')),
                ('lugarEntrega', models.CharField(default='', max_length=100, verbose_name='lugarEntrega')),
                ('IVA', models.CharField(choices=[('RI ', 'Responsable Inscripto'), ('CF', 'Consumidor Final'), ('EX ', 'Exento')], default='', max_length=5, verbose_name='IVA')),
                ('cantidad', models.DecimalField(decimal_places=2, default='1', max_digits=30, null=True, verbose_name='cantidad')),
                ('unidad', models.CharField(choices=[('TN ', 'TN'), ('LTS', 'LTS'), ('MT2', 'MT2')], default='', max_length=10, verbose_name='unidad')),
                ('numero', models.IntegerField(default='1', null=True, verbose_name='numero')),
                ('rancho', models.BooleanField(default=False)),
                ('observacion', models.CharField(default='', max_length=100, null=True, verbose_name='observacion')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('camion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.camion')),
                ('chofer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.chofer')),
                ('destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.cliente')),
                ('remolque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.remolque')),
            ],
            options={
                'db_table': 'RemitoVarios',
            },
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('OJR', 'OJR'), ('NAO', 'NAO')], default='', max_length=10, verbose_name='empresa')),
                ('numero', models.IntegerField(default='1', null=True, verbose_name='numero')),
                ('cantidadBarco', models.DecimalField(decimal_places=2, default='1', max_digits=30, null=True, verbose_name='cantidadBarco')),
                ('cantidadDeposito', models.DecimalField(decimal_places=2, default='1', max_digits=30, null=True, verbose_name='cantidadDeposito')),
                ('camion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.camion')),
                ('carga', models.ForeignKey(db_column='carga_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOJR.carga')),
                ('chofer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.chofer')),
                ('remolque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.remolque')),
                ('transporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.transporte')),
            ],
            options={
                'db_table': 'Remito',
            },
        ),
        migrations.CreateModel(
            name='Rancho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCarga', models.DateTimeField(default=django.utils.timezone.now)),
                ('litros', models.IntegerField(default='1', verbose_name='litros')),
                ('empresa', models.CharField(choices=[('OJR', 'OJR'), ('NAO', 'NAO')], default='', max_length=10, verbose_name='empresa')),
                ('origenMercaderia', models.CharField(default='Neuquen', max_length=20, verbose_name='OrigenMercaderia')),
                ('densidad', models.DecimalField(decimal_places=4, default='0.810', max_digits=10, null=True, verbose_name='densidad')),
                ('azufre', models.IntegerField(default='300', verbose_name='azufre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='precio')),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='impuestos')),
                ('emailEnviado', models.BooleanField()),
                ('barco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.barco')),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.combustible')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.puerto')),
            ],
            options={
                'db_table': 'Rancho',
            },
        ),
        migrations.CreateModel(
            name='ContactoAgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('telefono', models.CharField(default='', max_length=100, verbose_name='telefono')),
                ('correoElectronico', models.EmailField(default='', max_length=50, verbose_name='emailContacto')),
                ('enviaRancho', models.BooleanField(default=False)),
                ('agenciaMaritima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.agenciamaritima')),
            ],
            options={
                'db_table': 'ContactoAgencia',
            },
        ),
        migrations.AddField(
            model_name='carga',
            name='combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.combustible'),
        ),
        migrations.AddField(
            model_name='carga',
            name='puerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.puerto'),
        ),
        migrations.AddField(
            model_name='camion',
            name='transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.transporte'),
        ),
        migrations.CreateModel(
            name='ArmadoraPuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('agenciaMaritima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.agenciamaritima')),
                ('armadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.armadora')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.puerto')),
            ],
            options={
                'db_table': 'ArmadoraPuerto',
                'unique_together': {('armadora', 'puerto')},
            },
        ),
        migrations.AddField(
            model_name='armadora',
            name='puertos',
            field=models.ManyToManyField(through='appOJR.ArmadoraPuerto', to='appOJR.puerto'),
        ),
    ]
