# Generated by Django 4.2.2 on 2024-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerto',
            name='codigoAduana',
            field=models.IntegerField(null=True, verbose_name='codigoAduana'),
        ),
    ]
