# Generated by Django 4.2.2 on 2025-12-16 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("appOJR", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferenciaDeposito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="fecha"
                    ),
                ),
                (
                    "deposito_origen",
                    models.CharField(
                        default="", max_length=100, verbose_name="deposito_origen"
                    ),
                ),
                (
                    "deposito_destino",
                    models.CharField(
                        default="", max_length=100, verbose_name="deposito_destino"
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default="0",
                        max_digits=30,
                        null=True,
                        verbose_name="cantidad",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="observaciones",
                    ),
                ),
                (
                    "camion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appOJR.camion",
                    ),
                ),
                (
                    "chofer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appOJR.chofer",
                    ),
                ),
                (
                    "combustible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appOJR.combustible",
                    ),
                ),
            ],
            options={
                "db_table": "TransferenciaDeposito",
            },
        ),
    ]
