# Generated by Django 4.2.2 on 2024-04-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0002_puerto_codigoaduana'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='exentoRancho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remito',
            name='letraRancho',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='letraRancho'),
        ),
        migrations.AddField(
            model_name='remito',
            name='nroRancho',
            field=models.IntegerField(blank=True, default=0, verbose_name='nroRancho'),
            preserve_default=False,
        ),
    ]
