# Generated by Django 4.2.2 on 2025-12-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0002_transferenciadeposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='nombre')),
                ('direccion', models.CharField(blank=True, default='', max_length=100, verbose_name='direccion')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Deposito',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='transferenciadeposito',
            name='deposito_destino_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_destino', to='appOJR.deposito', verbose_name='deposito_destino_ref'),
        ),
        migrations.AddField(
            model_name='transferenciadeposito',
            name='deposito_origen_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_origen', to='appOJR.deposito', verbose_name='deposito_origen_ref'),
        ),
    ]
