# Generated by Django 4.2.2 on 2025-12-26 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0003_deposito_transferenciadeposito_deposito_destino_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='fechaRemito',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
