# Generated by Django 4.2.2 on 2025-12-30 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0004_carga_fecharemito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciadeposito',
            name='deposito_destino_ref',
        ),
        migrations.RemoveField(
            model_name='transferenciadeposito',
            name='deposito_origen_ref',
        ),
        migrations.AlterField(
            model_name='transferenciadeposito',
            name='deposito_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_destino', to='appOJR.deposito', verbose_name='deposito_destino'),
        ),
        migrations.AlterField(
            model_name='transferenciadeposito',
            name='deposito_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_origen', to='appOJR.deposito', verbose_name='deposito_origen'),
        ),
    ]
