# Generated by Django 4.2.2 on 2024-04-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0004_remove_remito_exentorancho_remove_remito_letrarancho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitovarios',
            name='producto',
            field=models.CharField(default='', max_length=100, verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='transporte',
            field=models.CharField(choices=[('OJR ', 'OJR'), ('NAO', 'NAO'), ('TRC', 'TRC')], default='', max_length=10, verbose_name='transporte'),
        ),
        migrations.AlterField(
            model_name='remitovarios',
            name='IVA',
            field=models.CharField(choices=[('RI ', 'Responsable Inscripto'), ('CF', 'Consumidor Final')], default='', max_length=5, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='remitovarios',
            name='transporte',
            field=models.CharField(choices=[('OJR ', 'Orlando Jorge Robert'), ('JPM', 'Juan Pedro Mairal')], default='', max_length=10, verbose_name='transporte'),
        ),
    ]
