# Generated by Django 4.2.2 on 2024-04-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0005_remitovarios_producto_alter_remito_transporte_and_more'),
    ]

    operations = [
        
    ]
