# Generated by Django 4.2.2 on 2024-04-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0006_transporte_camion_transporte'),
    ]

    operations = [
       
       
    ]
