# Generated by Django 4.2.2 on 2024-04-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0007_transporte_remove_camion_transporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(default='', max_length=10, verbose_name='abreviatura')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='nombre')),
            ],
            options={
                'db_table': 'Transporte',
            },
        )
       
    ]
