# Generated by Django 4.2.2 on 2024-04-25 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0008_transporte_camion_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='transporte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appOJR.transporte'),
            preserve_default=False,
        ),
    ]
