# Generated by Django 4.2.2 on 2024-05-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0010_alter_carga_nrorancho'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='ordenCompra',
            field=models.IntegerField(default=0, verbose_name='ordenCompra'),
        ),
    ]
