# Generated by Django 4.2.2 on 2024-05-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0011_carga_ordencompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='impresoraRemitos',
            field=models.CharField(choices=[('LaserNuria', 'LaserNuria'), ('Brother', 'Brother')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
