# Generated by Django 4.2.2 on 2024-05-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0012_configuracion_impresoraremitos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(default='', max_length=100, verbose_name='denominacion')),
                ('cuit', models.CharField(blank=True, default='', max_length=13, verbose_name='cuit')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.AddField(
            model_name='remitovarios',
            name='observacion',
            field=models.CharField(default='', max_length=100, verbose_name='observacion'),
        ),
        migrations.AlterField(
            model_name='remitovarios',
            name='IVA',
            field=models.CharField(choices=[('RI ', 'Responsable Inscripto'), ('CF', 'Consumidor Final'), ('EX ', 'Exento')], default='', max_length=5, verbose_name='IVA'),
        ),
        
    ]
