# Generated by Django 4.2.2 on 2024-05-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0013_cliente_remitovarios_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remito',
            name='transporte',
            field=models.CharField(choices=[('OJR ', 'Orlando Jorge Robert'), ('NAO', 'NAO'), ('TRC', 'Transcont')], default='', max_length=10, verbose_name='transporte'),
        ),
    ]
