# Generated by Django 4.2.2 on 2024-05-10 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0014_alter_remito_transporte'),
    ]

    operations = [
      
        migrations.CreateModel(
            name='ContactoAgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('telefono', models.CharField(default='', max_length=100, verbose_name='telefono')),
                ('correoElectronico', models.EmailField(default='', max_length=50, verbose_name='emailContacto')),
                ('enviaRancho', models.BooleanField(default=False)),
                ('agenciaMaritima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.agenciamaritima')),
            ],
            options={
                'db_table': 'ContactoAgencia',
            },
        ),
    ]
