# Generated by Django 4.2.2 on 2024-05-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0015_alter_remitovarios_destinatario_contactoagencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remito',
            name='cantidadBarco',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=30, null=True, verbose_name='cantidadBarco'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='cantidadDeposito',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=30, null=True, verbose_name='cantidadDeposito'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='transporte',
            field=models.CharField(choices=[('OJR ', 'Orlando Jorge Robert'), ('NAO', 'NAO'), ('VESPRINI', 'Vesprini'), ('TRC', 'Transcont')], default='', max_length=10, verbose_name='transporte'),
        ),
       
    ]
