# Generated by Django 4.2.2 on 2024-05-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0016_alter_remito_cantidadbarco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remolque',
            name='transporte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appOJR.transporte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remitovarios',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=30, null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='remitovarios',
            name='unidad',
            field=models.CharField(choices=[('TN ', 'TN'), ('LTS', 'LTS'), ('MT2', 'MT2')], default='', max_length=10, verbose_name='unidad'),
        ),
    ]
