# Generated by Django 4.2.2 on 2024-05-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0017_remolque_transporte_alter_remitovarios_cantidad_and_more'),
    ]

    operations = [
        
    ]
