# Generated by Django 4.2.2 on 2024-05-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0018_alter_remito_transporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remitovarios',
            name='empresa',
            field=models.CharField(choices=[('OJR', 'Orlando Jorge Robert'), ('NAO', 'NEW AMERICAN OIL')], default='', max_length=10, verbose_name='empresa'),
        ),
    ]
