# Generated by Django 4.2.2 on 2024-05-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0019_remitovarios_empresa'),
    ]

    operations = [
       
    ]
