# Generated by Django 4.2.2 on 2024-05-30 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0020_alter_remito_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='armadora',
            name='puerto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appOJR.puerto'),
            preserve_default=False,
        ),
        
    ]
