# Generated by Django 4.2.2 on 2024-05-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0021_armadora_puerto_alter_remitovarios_destinatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armadora',
            name='puerto',
        ),
        migrations.CreateModel(
            name='ArmadoraPuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('armadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.armadora')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.puerto')),
            ],
            options={
                'db_table': 'ArmadoraPuerto',
                'unique_together': {('armadora', 'puerto')},
            },
        ),
        migrations.AddField(
            model_name='armadora',
            name='puertos',
            field=models.ManyToManyField(through='appOJR.ArmadoraPuerto', to='appOJR.puerto'),
        ),
    ]
