# Generated by Django 4.2.2 on 2024-05-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0022_remove_armadora_puerto_alter_remito_transporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armadorapuerto',
            name='agenciaMaritima',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appOJR.agenciamaritima'),
            preserve_default=False,
        ),
        
    ]
