# Generated by Django 4.2.2 on 2024-06-03 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0023_armadorapuerto_agenciamaritima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='habilitadoAFIP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transporte',
            name='cuit',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='cuit'),
        ),
      
    ]
