# Generated by Django 4.2.2 on 2024-06-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0024_camion_habilitadoafip_transporte_cuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='empresa',
            field=models.CharField(choices=[('OJR', 'Orlando Jorge Robert'), ('NAO', 'NEW AMERICAN OIL')], default='', max_length=10, verbose_name='empresa'),
        ),
       
    ]
