# Generated by Django 4.2.2 on 2024-07-10 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0025_remito_empresa_alter_remito_transporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='ordenCompra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ordenCompra'),
        )
    ]
