# Generated by Django 4.2.2 on 2024-11-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0027_alter_carga_ordencompra_alter_remito_empresa_and_more'),
    ]

    operations = [
                migrations.AlterField(
            model_name='remitovarios',
            name='transporte',
            field=models.CharField(choices=[('OJR ', 'Orlando Jorge Robert'), ('JPM', 'Juan Pedro Mairal'), ('VESPRINI', 'Vesprini'), ('TRC', 'Transcont')], default='', max_length=10, verbose_name='transporte'),
        ),
    ]
