# Generated by Django 4.2.2 on 2024-12-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0028_alter_remito_empresa_alter_remito_transporte_and_more'),
    ]

    operations = [
           
    ]
