# Generated by Django 4.2.2 on 2025-05-06 21:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0029_producto_remitovarios_rancho_alter_remito_empresa_and_more'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Rancho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCarga', models.DateTimeField(default=django.utils.timezone.now)),
                ('litros', models.IntegerField(default='1', verbose_name='litros')),
                ('empresa', models.CharField(choices=[('OJR', 'OJR'), ('NAO', 'NAO')], default='', max_length=10, verbose_name='empresa')),
                ('densidad', models.DecimalField(decimal_places=4, default='0.810', max_digits=10, null=True, verbose_name='densidad')),
                ('azufre', models.IntegerField(default='300', verbose_name='azufre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='precio')),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='impuestos')),
                ('barco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.barco')),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.combustible')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOJR.puerto')),
            ],
            options={
                'db_table': 'Rancho',
            },
        ),
    ]
