# Generated by Django 4.2.2 on 2025-05-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0030_producto_alter_remito_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(default='', max_length=100, verbose_name='denominacion')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.AddField(
            model_name='rancho',
            name='emailEnviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remitovarios',
            name='rancho',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='remito',
            name='empresa',
            field=models.CharField(choices=[('OJR', 'OJR'), ('NAO', 'NAO')], default='', max_length=10, verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='remito',
            name='transporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.transporte'),
        ),
        migrations.AlterField(
            model_name='remitovarios',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOJR.cliente'),
        ),
        migrations.AlterField(
            model_name='remitovarios',
            name='empresa',
            field=models.CharField(choices=[('OJR', 'OJR'), ('NAO', 'NAO')], default='', max_length=10, verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='remitovarios',
            name='observacion',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='observacion'),
        ),
    ]
