# Generated by Django 4.2.2 on 2025-08-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0031_producto_rancho_emailenviado_remitovarios_rancho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rancho',
            name='origenMercaderia',
            field=models.CharField(default='Neuquen', max_length=20, verbose_name='OrigenMercaderia'),
        ),
        migrations.AlterField(
            model_name='rancho',
            name='emailEnviado',
            field=models.BooleanField(),
        ),
    ]
