# Generated by Django 4.2.2 on 2025-08-18 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appOJR', '0032_rancho_origenmercaderia_alter_rancho_emailenviado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carga',
            name='fechaHoraInicio',
        ),
        migrations.AddField(
            model_name='carga',
            name='fechaInicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carga',
            name='horaInicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
